### ISSUE TITLE
How long until next support?

### ISSUE THREAD

**Issue by Melvasul** [cwtools/cwtools#27]
Hello there :)

Since 1.30 has been released I've been having some troubles with the extension setting.

Every setting was as before, but I just can't have any more autocompletion or error checking.
When tried to reload the extension I get the
`loading project...`
but nothing more
![2020 06 10-09 35](https://user-images.githubusercontent.com/11297488/84240096-c9f5d300-aafd-11ea-9378-3647b32395e8.png)

Is there something I can do to try to force the new game version? or should I just wait for the next extension setting?

thanks in advance, 
have a nice day :)

**Comment by tboby** [comment]
@Melvasul Sorry for the slow response, busy week.

Few things to check/try:
1. What happens if you "open folder" on "missionsdev" instead of the parent folder?
2. What language is showing in the bottom right? (eu4, paradox, etc)
3. Check your vanilla folder is set correctly in settings

I should be able to work out what's going on with some log files. Note, this will have your username in it, so feel free to redact that.
1. Open cwtools and wait a few minutes to be sure it's stuck.
2. View, Output
3. In the panel that opens, Select "Paradox language server" in the dropdown. If there are multiple, pick the one with the most logs
4. Paste that in here if small enough, otherwise perhaps drop it in a pastebin or similar

Sorry you're having problems!

**Comment by Melvasul** [comment]
Hello there
I've tried, in the meantime to do some of those fixes and I think I found the problem.
In the same workspace, I had one folder that no longer exists

Creating a new workspace with all the folders I needed and without the removed folder seems to be working.
![2020 06 15-14 34](https://user-images.githubusercontent.com/11297488/84658005-7a584280-af15-11ea-9b70-06f595abad2d.png)

if you see two `Europa Universalis IV` folders is due to one being the `Steam `one and the other one being the `Document` folder.
This because, at the first try, I had to add the parent `\Documents\Paradox Interactive\Europa Universalis IV\` folder, because without it (with just the mod folder) the script would not run, although I did not test this enough to say "hey, it's 100% a bug"

**Comment by tboby** [comment]
A non-existent folder would do probably have been enough!

cwtools will treat each folder in the workspace as a unique entry, and classify them into one of:
a. Vanilla
b. Multiple mod directory (containing .mod files)
c. Direct mod folder (most common)

And it relies on there being a folder "Europa Universalis IV" somewhere in the path above to detect this is a script folder.

So in your case you should be able to drop that mod folder now. You can probably drop vanilla EU4 as well to speed up loading time, and rely on the cached files.

If you use F12 or the "Cwtools loaded files" you can still view the vanilla files when you need them :)
